version: "3.2"
services:
  frontend:
    image: "node:10"
    volumes:
      - ./frontend/:/home/node/app
  backend:
    image: "mcr.microsoft.com/dotnet/core/sdk:3.0"
    entrypoint: "dotnet run --project /app/BlogApi.csproj"
    working_dir: /app
    volumes:
      - ./backend/:/app
