version: "3.2"
services:
  frontend:
    #user: "node"
    working_dir: /home/node/app
    ports:
      - "4200:4200"
    command: "npm start"
    depends_on:
      - backend
  backend:
    build: ./backend/.
    working_dir: /app
    expose:
      - "5001"
    depends_on:
      - database
  database:
    image: "mysql:8"
    env_file: "example.env"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql
